# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

WORKDIR /app

# Copy package definitions
COPY package*.json ./

# Install dependencies without running scripts
RUN npm install --ignore-scripts

# Copy the rest of the files
COPY . .

# Build the project
RUN npm run build

# Expose necessary port if required (MCP server uses stdio, so typically not needed)

# Start the MCP server
CMD ["npm", "start"]
